### ISSUE TITLE
Creation of sumo branch

### ISSUE THREAD

**Issue by hbuchsbaum** [kraj/meta-altera#110]
Living on Yocto sumo meant using the master branch until Feb 24. Now there has been a move to thud with e1e47723d3ba4e87cfadbffbf5df8d7a253d8186, so people like me would really appreciate the creation of a sumo branch at aacec0cebc5399b98497a9875dcde306d17a9518, which marks the latest sumo compatible version to be able to continue using sumo easily.

**Comment by kraj** [comment]
@hbuchsbaum can you send a patch to make it
`LAYERSERIES_COMPAT_meta-altera = "sumo thud"`

**Comment by salerio-gs** [comment]
@kraj I just created a PR for this as I need it too.

**Comment by dwesterg** [comment]
this has been done.
