### ISSUE TITLE
Getting error with bitbake virtual/kernel on lts 5.4.84

### ISSUE THREAD

**Issue by tungdt113** [kraj/meta-altera#219]
Hi all,
when i  had run bitbake virtual/kernel with linux-altera-lts 5.4.84 , i got this error
![image](https://user-images.githubusercontent.com/64633842/109094780-23199b80-774d-11eb-8aec-653a5d94c8b7.png)

**Comment by Deliver88** [comment]
Hello,

how to figure this config out, to use it usin linux-altera-lts-5.4

cat << EOF > .repo/local_manifests/de10-nano.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<manifest>                                                                      
        <remove-project name="kraj/meta-altera" />                              
        <remove-project name="koenkooi/meta-photography" />                     
        <remove-project name="openembedded/meta-linaro" />                      
        <project name="openembedded/meta-linaro" path="layers/meta-linaro" remote="linaro" revision="992eaa0a1969c2056a5321c122eaa8cd808c1c82" upstream="master"/>
        <project remote="github"  name="kraj/meta-altera" path="layers/meta-altera" revision="cf7fc462cc6a5e82f2de76bb21e09675be7ae316"/>
        <project name="01org/meta-de10-nano" path="layers/meta-de10-nano" remote="github" revision="refs/tags/VERSION-2017.03.31"/>
</manifest> 
EOF


whould this here

cat << EOF > .repo/local_manifests/de10-nano.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<manifest>                                                                      
        <remove-project name="kraj/meta-altera" />                              
        <remove-project name="koenkooi/meta-photography" />                     
        <remove-project name="openembedded/meta-linaro" />                      
        <project name="openembedded/meta-linaro" path="layers/meta-linaro" remote="linaro" revision="992eaa0a1969c2056a5321c122eaa8cd808c1c82" upstream="master"/>
        <project remote="github"  name="kraj/meta-altera" path="layers/meta-altera" revision="13ea0b332b7e48cd19010919cedd4620808fad46"/>
        <project name="01org/meta-de10-nano" path="layers/meta-de10-nano" remote="github" revision="refs/tags/VERSION-2017.03.31"/>
</manifest> 
EOF


work ? which "openembedded/meta-linaro" revision is the correct one?

Which angstrom version should be taken? for the example above used angstrom-v2016.12-yocto2.2  for the rocko branch. Which one should be used here for the de10-nano board?

Thanks a lot.
