### ISSUE TITLE
yocto worrior project with meta-altera

### ISSUE THREAD

**Issue by burkulesomesh43** [kraj/meta-altera#242]
Hi Kraj,
I want to build yocto for cyclone v fpga altera board.

from below document, it directs to yocto worrior project but meta-altera master branch.
![image](https://github.com/user-attachments/assets/53be301e-bb48-4b53-b72f-b1370daaaf7e)

https://www.rocketboards.org/foswiki/Documentation/BuildingYoctoOrAngstromForSoCFPGA

but metra-altera master branch doesn't support worrior.

anything wrong with documentation or I'm missing something?

BR,
Somesh

**Comment by kraj** [comment]
you have to go back in time and checkout older version of master or perhaps use `dunfell` branch of meta-altera
