### ISSUE TITLE
u-boot.do_compile function failed on pyro

### ISSUE THREAD

**Issue by lucchristin** [kraj/meta-altera#79]
Hi,

I'm trying to build a Kernel image using the Yocto project for the arria10 board, but I got an error when running bitbake virtual/bootloader.

The error is the following:
```
 Loading cache: 100% |##########################################################################################################################################################################################################| Time: 0:00:00
Loaded 1435 entries from dependency cache.
Parsing recipes: 100% |########################################################################################################################################################################################################| Time: 0:00:00
Parsing of 925 .bb files complete (924 cached, 1 parsed). 1436 targets, 90 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.34.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "universal-4.8"
TARGET_SYS        = "arm-poky-linux-gnueabi"
MACHINE           = "arria10"
DISTRO            = "poky"
DISTRO_VERSION    = "2.3.3"
TUNE_FEATURES     = "arm armv7a vfp neon callconvention-hard cortexa9"
TARGET_FPU        = "hard"
meta              
meta-poky         
meta-yocto-bsp    = "pyro:d8f5ae15b9d16d4e348570bb016b876d51989131"
meta-altera       = "pyro:565d8443d6dcba4e25924ba049ba81e080f87884"
meta-linaro-toolchain = "pyro:74dacb34c13d1c85fe4627a890b9c04940f9ffeb"

Initialising tasks: 100% |#####################################################################################################################################################################################################| Time: 0:00:00
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: u-boot-socfpga-v2014.10-r1 do_compile: oe_runmake failed
ERROR: u-boot-socfpga-v2014.10-r1 do_compile: Function failed: do_compile (log file is located at /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/temp/log.do_compile.23555)
ERROR: Logfile of failure stored in: /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/temp/log.do_compile.23555
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 4 CROSS_COMPILE=arm-poky-linux-gnueabi- CC=arm-poky-linux-gnueabi-gcc  --sysroot=/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot V=1 HOSTCC=gcc  -isystem/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/usr/include -O2 -pipe -L/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/usr/lib -L/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/lib -Wl,-rpath-link,/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/usr/lib -Wl,-rpath-link,/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/lib -Wl,-rpath,/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/usr/lib -Wl,-rpath,/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/lib -Wl,-O1 -C /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/u-boot-socfpga-v2014.10 O=/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/build/socfpga_arria10_defconfig socfpga_arria10_defconfig
| ERROR: oe_runmake failed
| make: Entering directory `/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/u-boot-socfpga-v2014.10'
| make: *** No rule to make target `socfpga_arria10_defconfig'.  Stop.
| make: Leaving directory `/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/u-boot-socfpga-v2014.10'
| ERROR: Function failed: do_compile (log file is located at /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/temp/log.do_compile.23555)
ERROR: Task (/home/lch/yoctoAltera/poky/meta-altera/recipes-bsp/u-boot/u-boot-socfpga_v2014.10.bb:do_compile) failed with exit code '1'' 
 ```

I'm using the meta-altera layer and meta-linaro edition with the following local.conf:
```
 MACHINE = "arria10"

GCCVERSION = "linaro-5.2"
SDKGCCVERSION = "linaro-5.2"
DEFAULTTUNE = "cortexa9hf-neon"

PREFERRED_PROVIDER_virtual/kernel = "linux-altera-ltsi"
PREFERRED_VERSION_linux-altera-ltsi = "4.1%" 

```

Best regards,
Luc

**Comment by kraj** [comment]
On 4/3/18 2:21 AM, Luc.Christin wrote:
> Hi,
> 
> I'm trying to build a Kernel image using the Yocto project for the
> arria10 board, but I got an error when running bitbake virtual/bootloader.
> 
> The error is the following:
> 
> |Loading cache: 100%
> |##########################################################################################################################################################################################################|
> Time: 0:00:00 Loaded 1435 entries from dependency cache. Parsing
> recipes: 100%
> |########################################################################################################################################################################################################|
> Time: 0:00:00 Parsing of 925 .bb files complete (924 cached, 1 parsed).
> 1436 targets, 90 skipped, 0 masked, 0 errors. NOTE: Resolving any
> missing task queue dependencies Build Configuration: BB_VERSION =
> "1.34.0" BUILD_SYS = "x86_64-linux" NATIVELSBSTRING = "universal-4.8"
> TARGET_SYS = "arm-poky-linux-gnueabi" MACHINE = "arria10" DISTRO =
> "poky" DISTRO_VERSION = "2.3.3" TUNE_FEATURES = "arm armv7a vfp neon
> callconvention-hard cortexa9" TARGET_FPU = "hard" meta meta-poky
> meta-yocto-bsp = "pyro:d8f5ae15b9d16d4e348570bb016b876d51989131"
> meta-altera = "pyro:565d8443d6dcba4e25924ba049ba81e080f87884"
> meta-linaro-toolchain = "pyro:74dacb34c13d1c85fe4627a890b9c04940f9ffeb"
> Initialising tasks: 100%
> |#####################################################################################################################################################################################################|
> Time: 0:00:00 NOTE: Executing SetScene Tasks NOTE: Executing RunQueue
> Tasks ERROR: u-boot-socfpga-v2014.10-r1 do_compile: oe_runmake failed
> ERROR: u-boot-socfpga-v2014.10-r1 do_compile: Function failed:
> do_compile (log file is located at
> /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/temp/log.do_compile.23555)
> ERROR: Logfile of failure stored in:
> /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/temp/log.do_compile.23555
> Log data follows: | DEBUG: Executing shell function do_compile | NOTE:
> make -j 4 CROSS_COMPILE=arm-poky-linux-gnueabi-
> CC=arm-poky-linux-gnueabi-gcc
> --sysroot=/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot
> V=1 HOSTCC=gcc
> -isystem/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/usr/include
> -O2 -pipe
> -L/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/usr/lib
> -L/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/lib
> -Wl,-rpath-link,/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/usr/lib
> -Wl,-rpath-link,/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/lib
> -Wl,-rpath,/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/usr/lib
> -Wl,-rpath,/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/lib
> -Wl,-O1 -C
> /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/u-boot-socfpga-v2014.10
> O=/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/build/socfpga_arria10_defconfig
> socfpga_arria10_defconfig | ERROR: oe_runmake failed | make: Entering
> directory
> `/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/u-boot-socfpga-v2014.10'
> | make: *** No rule to make target `socfpga_arria10_defconfig'. Stop. |
> make: Leaving directory
> `/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/u-boot-socfpga-v2014.10'
> | ERROR: Function failed: do_compile (log file is located at
> /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/temp/log.do_compile.23555)
> ERROR: Task
> (/home/lch/yoctoAltera/poky/meta-altera/recipes-bsp/u-boot/u-boot-socfpga_v2014.10.bb:do_compile)
> failed with exit code '1'' |
> 
> I'm using the meta-altera layer and meta-linaro edition with the
> following local.conf:
> 
> |MACHINE = "arria10" GCCVERSION = "linaro-5.2" SDKGCCVERSION =
> "linaro-5.2" DEFAULTTUNE = "cortexa9hf-neon"
> PREFERRED_PROVIDER_virtual/kernel = "linux-altera-ltsi"
> PREFERRED_VERSION_linux-altera-ltsi = "4.1%" |
> 

Can you remove these pinnings and try with latest master or rocko release ?

**Comment by lucchristin** [comment]
I got the same problem, with using only MACHINE="arria10" and changing package_rpm to package_ipk,
if I don't say MACHINE="arria10" there isn't any recipes to fullfill virtual/bootloader.

here the error: 
````
ERROR: u-boot-socfpga-v2014.10-r1 do_populate_lic: QA Issue: u-boot-socfpga: LIC_FILES_CHKSUM points to an invalid file: /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/u-boot-socfpga-v2014.10/Licenses/README [license-checksum]
ERROR: u-boot-socfpga-v2014.10-r1 do_compile: oe_runmake failed
ERROR: u-boot-socfpga-v2014.10-r1 do_compile: Function failed: do_compile (log file is located at /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/temp/log.do_compile.30579)
ERROR: Logfile of failure stored in: /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/temp/log.do_compile.30579
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 4 CROSS_COMPILE=arm-poky-linux-gnueabi- CC=arm-poky-linux-gnueabi-gcc  --sysroot=/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot V=1 HOSTCC=gcc  -isystem/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/usr/include -O2 -pipe -L/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/usr/lib -L/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/lib -Wl,-rpath-link,/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/usr/lib -Wl,-rpath-link,/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/lib -Wl,-rpath,/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/usr/lib -Wl,-rpath,/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/lib -Wl,-O1 -C /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/u-boot-socfpga-v2014.10 O=/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/build/socfpga_arria10_defconfig socfpga_arria10_defconfig
| ERROR: oe_runmake failed
| make: Entering directory `/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/u-boot-socfpga-v2014.10'
| make: *** No rule to make target `socfpga_arria10_defconfig'.  Stop.
| make: Leaving directory `/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/u-boot-socfpga-v2014.10'
| ERROR: Function failed: do_compile (log file is located at /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/temp/log.do_compile.30579)
ERROR: Task (/home/lch/yoctoAltera/poky/meta-altera/recipes-bsp/u-boot/u-boot-socfpga_v2014.10.bb:do_compile) failed with exit code '1'
````

**Comment by kraj** [comment]
Can you change SRCREV = "2a2102e92e470beec51d8b2dea8323cfc92f92b1"

in

recipes-bsp/u-boot/u-boot-socfpga_v2014.10.bb

and see if that helps ?

**Comment by lucchristin** [comment]
Same problem
````
ERROR: u-boot-socfpga-v2014.10-r1 do_populate_lic: QA Issue: u-boot-socfpga: LIC_FILES_CHKSUM points to an invalid file: /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/u-boot-socfpga-v2014.10/Licenses/README [license-checksum]
ERROR: u-boot-socfpga-v2014.10-r1 do_compile: oe_runmake failed
ERROR: u-boot-socfpga-v2014.10-r1 do_compile: Function failed: do_compile (log file is located at /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/temp/log.do_compile.10349)
ERROR: Logfile of failure stored in: /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/temp/log.do_compile.10349
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 4 CROSS_COMPILE=arm-poky-linux-gnueabi- CC=arm-poky-linux-gnueabi-gcc  --sysroot=/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot V=1 HOSTCC=gcc  -isystem/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/usr/include -O2 -pipe -L/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/usr/lib -L/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/lib -Wl,-rpath-link,/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/usr/lib -Wl,-rpath-link,/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/lib -Wl,-rpath,/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/usr/lib -Wl,-rpath,/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/recipe-sysroot-native/lib -Wl,-O1 -C /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/u-boot-socfpga-v2014.10 O=/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/build/socfpga_arria10_defconfig socfpga_arria10_defconfig
| ERROR: oe_runmake failed
| make: Entering directory `/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/u-boot-socfpga-v2014.10'
| make: *** No rule to make target `socfpga_arria10_defconfig'.  Stop.
| make: Leaving directory `/home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/u-boot-socfpga-v2014.10'
| ERROR: Function failed: do_compile (log file is located at /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/temp/log.do_compile.10349)
ERROR: Task (/home/lch/yoctoAltera/poky/meta-altera/recipes-bsp/u-boot/u-boot-socfpga_v2014.10.bb:do_compile) failed with exit code '1'
````

**Comment by lucchristin** [comment]
Hi Kraj,

Do you provide anything else to the bitbake, like a .dts? or a bitstream?

What can I do to find more information about the error?
I would really like to solve it as it's the only step missing.

Best regards,
Luc.

**Comment by lucchristin** [comment]
Hi,

It seem there is a problem in the fetching of those files, there are downloaded but not in the good directories, doing it manually solve the problem. Pay attention to copy the .git, if it's not there it will give an issue.

To solve this issue, you need to download the missing files in the /home/lch/yoctoAltera/poky/build/tmp/work/arria10-poky-linux-gnueabi/u-boot-socfpga/v2014.10-r1/u-boot-socfpga-v2014.10 directories, to do so just git clone https://github.com/altera-opensource/u-boot-socfpga and copy/move all the files/directories to the u-boot-socfpga-v2014.10.

Best regards,
Luc

**Comment by kraj** [comment]
pyro is not maintained anymore.
