### ISSUE TITLE
arria10 kernel 4.15 do_fetch failing

### ISSUE THREAD

**Issue by fwmiller** [kraj/meta-altera#88]
Looking over at the linux-altera site, it appears that kernel 4.15 is no longer available.  Is there an update here for a later kernel?

**Comment by dwesterg** [comment]
i havent tested yet, but feel free to try

https://github.com/dwesterg/meta-altera/tree/rocko

**Comment by kraj** [comment]
can you recheck again after git pull

**Comment by dwesterg** [comment]
I'm testing an update to add 4.17 as we speak..

**Comment by fwmiller** [comment]
latest updated fixed this!  Thanks!
