### ISSUE TITLE
Missing DE10-Nano target

### ISSUE THREAD

**Issue by panekk** [kraj/meta-altera#91]
Hello,

What happened to DE10-Nano target? I remember I was able to build kernel for it, but right now I'm getting `No rule to make target 'arch/arm/boot/dts/socfpga_cyclone5_de10_nano.dtb'`.  I'm trying to build 4.16 kernel. My local meta-altera and poky repositories are up to date with origin/rocko.

In `build` folder I have `socfpga_cyclone5_de10_nano.dts` file from some previous build, but I can't find it in any current repository. For now I solved it by making fork of `linux-socfpga` and adding missing `dts`, but I'm curious if it's the right way and why `dts` is missing out of the box.

Best regards,
Kamil

**Comment by dwesterg** [comment]
de10 was never in meta-altera, it is in meta-de10-nano available at 

https://github.com/intel/meta-de10-nano

thanks,
Dalon
