### ISSUE TITLE
Adding kernel config

### ISSUE THREAD

**Issue by fwmiller** [kraj/meta-altera#92]
I'm having a little trouble adding some kernel configs.  I've added a file called kernel_config_fragment.cfg to the location yocto/poky/meta-altera/recipes-kernel/linux/files  but the kernel build does not seem to be picking it up.  Can you advise?

Thanks,
FM

**Comment by kraj** [comment]
@fwmiller you also need to add it to SRC_URI something like
```
SRC_URI += "file://kernel_config_fragment.cfg"
```

**Comment by fwmiller** [comment]
Thats got it.  Thanks!
